use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=installer/wow-sim.ico");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=tests");

    generate_integration_test_harness();

    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os != "windows" {
        return;
    }

    let mut res = winresource::WindowsResource::new();
    res.set_icon("installer/wow-sim.ico");
    if let Err(error) = res.compile() {
        // On hosts without a usable resource compiler the binary should still
        // link; surface the failure as a cargo warning instead of aborting.
        println!("cargo:warning=failed to embed Windows icon resource: {error}");
    }
}

fn generate_integration_test_harness() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let tests_dir = manifest_dir.join("tests");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("out dir"));
    let harness_path = out_dir.join("integration_tests.rs");

    let mut module_files = discover_top_level_test_modules(&tests_dir);
    module_files.sort();

    let mut contents = String::from("// Generated by build.rs. Do not edit.\n");
    contents.push_str(&format!(
        "#[allow(dead_code, unused_imports)]\n#[macro_use]\n#[path = {:?}]\npub mod common;\n\n",
        tests_dir.join("common/mod.rs")
    ));
    for perf_module in discover_perf_helper_modules(&tests_dir.join("perf")) {
        let module_name = format!("perf_{}", module_name_for_path(&perf_module));
        contents.push_str(&format!(
            "#[cfg(feature = \"gui\")]\n#[allow(dead_code, unused_imports)]\n#[path = {perf_module:?}]\npub(crate) mod {module_name};\n\n"
        ));
    }
    contents.push_str(&format!(
        "#[allow(dead_code, unused_imports)]\n#[path = {:?}]\npub(crate) mod support;\n\n",
        tests_dir.join("c_item_api/support.rs")
    ));
    contents.push_str(&format!(
        "#[allow(dead_code, unused_imports)]\n#[path = {:?}]\npub(crate) mod token_ui_fixtures;\n\n",
        tests_dir.join("common/token_ui_fixtures.rs")
    ));

    for file in module_files {
        let module_name = module_name_for_path(&file);
        contents.push_str(&format!(
            "#[allow(dead_code, unused_imports)]\n#[path = {file:?}]\nmod {module_name};\n\n"
        ));
    }

    std::fs::write(harness_path, contents).expect("write integration test harness");
}

fn discover_top_level_test_modules(tests_dir: &Path) -> Vec<PathBuf> {
    let entries = std::fs::read_dir(tests_dir).expect("read tests dir");
    entries
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("rs"))
        .filter(|path| should_include_in_integration_harness(path))
        .collect()
}

fn discover_perf_helper_modules(perf_dir: &Path) -> Vec<PathBuf> {
    let mut modules: Vec<_> = std::fs::read_dir(perf_dir)
        .expect("read perf test helper dir")
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("rs"))
        .collect();
    modules.sort();
    modules
}

fn should_include_in_integration_harness(path: &Path) -> bool {
    let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
        return false;
    };
    !matches!(
        file_name,
        "blizzard_addon_closure_harness.rs"
            | "blizzard_addon_smoke_targets.rs"
            | "frame_positions.rs"
            | "integration.rs"
            | "mists_addonlist_interactions.rs"
            | "visualizer_coordinate_raster.rs"
    )
}

fn module_name_for_path(path: &Path) -> String {
    path.file_stem()
        .and_then(|stem| stem.to_str())
        .expect("test module stem")
        .to_string()
}
