//! rilua equivalents of admin_api.rs, admin_api_world.rs,
//! admin_api_mail_premade.rs, admin_combat.rs, and admin_encounter.rs.
//!
//! Registers the `A_Admin` namespace as RustFn closures on rilua's VM.
//! Each function accesses SimState via `borrow_state` / `borrow_state_mut`
//! from `methods`, using `FromStack` for argument extraction.
//!
//! # generated_stubs.rs approach
//!
//! generated_stubs.rs contains ~962 auto-generated stub functions.
//! These will be regenerated by tools/generate_stubs.py with rilua output
//! rather than converted by hand. See the script for the template.

use crate::lua_api::game_data::{AuraInfo, CastingState, SpellCooldownState};
use crate::lua_api::methods::{borrow_state, borrow_state_mut};
use crate::lua_api::state::DEFAULT_LFG_QUEUE_POP_DELAY_SECONDS;
use crate::lua_api::state_types::SecondaryPowerState;
use crate::lua_bridge::{FromStack, TableBuilder};
use rilua::vm::closure::RustFn;
use rilua::vm::state::LuaState;
use rilua::{LuaResult, Val};

// Focused sub-modules — each holds one A_Admin section and keeps the
// entry-point file small. The parent TableBuilder chain wires these up.
use super::admin_actionbars_bags::{
    add_bag_item, add_guild_bank_item, clear_action_bars, clear_action_slot, clear_bags,
    clear_guild_bank, remove_bag_item, set_action_slot, set_merchant_items, set_pet_action_slot,
};
use super::admin_addons::register_test_addon;
use super::admin_auction_house::{
    add_auction_bid, add_auction_browse_result, add_auction_commodity_search_result,
    add_auction_item_search_result, add_auction_replicate_item, add_owned_auction,
    clear_auction_bids, clear_auction_browse_results, clear_auction_commodity_search_results,
    clear_auction_item_search_results, clear_auction_replicate_items, clear_owned_auctions,
    set_auction_throttle_ready,
};
use super::admin_buffs::{add_buff, add_debuff, clear_buffs, remove_buff};
use super::admin_collections::{
    add_transmog, add_transmog_appearance, collect_campsite, collect_heirloom, collect_mount,
    collect_pet, collect_toy, earn_achievement, has_achievement, remove_transmog,
    set_achievement_earned, set_campsite_collected, set_mount_collected, set_pet_collected,
    set_toy_collected, set_transmog_for_slot, uncollect_campsite, uncollect_heirloom,
    uncollect_mount, uncollect_pet, uncollect_toy,
};
use super::admin_crafting::{
    clear_known_recipes, learn_recipe, relearn_profession, seed_reagents_for_recipe,
    set_reagent_count, set_selected_profession, unlearn_profession, unlearn_recipe,
};
use super::admin_encounter::{
    add_loot_item, clear_loot, end_loot_roll, get_last_loot_roll_choice, simulate_boss_kill,
    start_loot_roll,
};
use super::admin_equipment::{equip_item, unequip_item};
use super::admin_events::{fire_event_admin, toggle_debug_anchors, toggle_debug_borders};
use super::admin_interactions::{close_mailbox, open_mailbox};
use super::admin_mail::{add_mail, clear_inbox, set_inbox_count};
use super::admin_movement::{set_falling, set_flying, set_mounted, set_moving, set_swimming};
use super::admin_party_target_helpers::{
    clear_focus, clear_target, kill_party_member, res_party_member, set_focus, set_focus_health,
    set_focus_power, set_focus_type, set_party_leader, set_party_member, set_party_member_health,
    set_party_size, set_rot_damage, set_target, set_target_power, set_target_type,
};
use super::admin_premade::{add_premade_listing, clear_premade_listings, update_premade_listing};
use super::admin_pvp_guild::{
    clear_guild, join_guild, leave_guild, set_guild_info, set_honor_level, set_pvp_enabled,
};
use super::admin_spec::{reset_talents, set_spec, set_talent_rank, set_talent_selection};
use super::admin_vault::{clear_vault, set_vault_activity, set_vault_rewards};
use super::admin_zone_economy::{
    set_alt_key_down, set_bind_location, set_control_key_down, set_guild_emblem, set_guild_ranks,
    set_in_instance, set_instance_info, set_item_level, set_meta_key_down, set_money,
    set_mouse_over_frame, set_mouse_position, set_net_stats, set_shift_key_down,
    set_store_frame_shown, set_sub_zone, set_timerunning_season_id, set_zone, set_zone_pvp,
};

// ── Entry point ──────────────────────────────────────────────────────────────

/// Register the `A_Admin` namespace on rilua's global table.
pub fn register_all(lua: &mut rilua::Lua) -> LuaResult<()> {
    use rilua::LuaApiMut;

    let builder = TableBuilder::new(lua.state_mut());
    let builder = register_player(builder)?;
    let builder = register_combat_casting(builder)?;
    let builder = register_targeting_party(builder)?;
    let builder = register_world(builder)?;
    let builder = register_collections_pvp(builder)?;
    let builder = register_inventory_misc(builder)?;
    let admin_val = builder.build();

    LuaApiMut::set_global_val(lua, "A_Admin", admin_val)?;
    super::group_queries::register_all(lua.state_mut());
    Ok(())
}

fn register_player(b: TableBuilder) -> LuaResult<TableBuilder> {
    b.set_function("SetPlayerName", set_player_name)?
        .set_function("SetPlayerClass", set_player_class)?
        .set_function("SetPlayerRace", set_player_race)?
        .set_function("SetPlayerLevel", set_player_level)?
        .set_function("SetPlayerSex", set_player_sex)?
        .set_function("SetPlayerHealth", set_player_health)?
        .set_function("SetPlayerPower", set_player_power)?
        .set_function("SetSpec", set_spec)?
        .set_function("SetTalentRank", set_talent_rank)?
        .set_function("SetTalentSelection", set_talent_selection)?
        .set_function("ResetTalents", reset_talents)?
        .set_function("AddBuff", add_buff)?
        .set_function("AddDebuff", add_debuff)?
        .set_function("RemoveBuff", remove_buff)?
        .set_function("ClearBuffs", clear_buffs)?
        .set_function("EquipItem", equip_item)?
        .set_function("UnequipItem", unequip_item)
}

fn register_combat_casting(b: TableBuilder) -> LuaResult<TableBuilder> {
    b.set_function("SetInCombat", set_in_combat)?
        .set_function("SetResting", set_resting)?
        .set_function("SetFrameProtected", set_frame_protected)?
        .set_function("SetCasting", set_casting)?
        .set_function("StopCasting", stop_casting)?
        .set_function("SetGCD", set_gcd)?
        .set_function("SetSpellCooldown", set_spell_cooldown)?
        .set_function("SetMoving", set_moving)?
        .set_function("SetMounted", set_mounted)?
        .set_function("SetFlying", set_flying)?
        .set_function("SetFalling", set_falling)?
        .set_function("SetSwimming", set_swimming)
}

fn register_targeting_party(b: TableBuilder) -> LuaResult<TableBuilder> {
    b.set_function("SetTarget", set_target)?
        .set_function("ClearTarget", clear_target)?
        .set_function("SetFocus", set_focus)?
        .set_function("ClearFocus", clear_focus)?
        .set_function("SetTargetHealth", set_target_health)?
        .set_function("SetTargetPower", set_target_power)?
        .set_function("SetFocusPower", set_focus_power)?
        .set_function("SetTargetType", set_target_type)?
        .set_function("SetFocusType", set_focus_type)?
        .set_function("SetFocusHealth", set_focus_health)?
        .set_function("SetPartySize", set_party_size)?
        .set_function("SetPartyLeader", set_party_leader)?
        .set_function("SetPartyMember", set_party_member)?
        .set_function("SetPartyMemberHealth", set_party_member_health)?
        .set_function("KillPartyMember", kill_party_member)?
        .set_function("ResPartyMember", res_party_member)?
        .set_function("SetRotDamage", set_rot_damage)?
        .set_function("SetEnemyPool", super::targeting_verbs::admin_set_enemy_pool)
}

fn register_world(b: TableBuilder) -> LuaResult<TableBuilder> {
    let b = register_zone_and_economy(b)?;
    let b = register_modifier_keys(b)?;
    let b = register_guild_and_game_rules(b)?;
    let b = register_services(b)?;
    let b = register_inventory_and_mail(b)?;
    register_vault_and_premade(b)
}

fn register_zone_and_economy(b: TableBuilder) -> LuaResult<TableBuilder> {
    b.set_function("SetZone", set_zone)?
        .set_function("SetSubZone", set_sub_zone)?
        .set_function("SetBindLocation", set_bind_location)?
        .set_function("SetInstanceInfo", set_instance_info)?
        .set_function("SetInInstance", set_in_instance)?
        .set_function("SetMoney", set_money)?
        .set_function("SetItemLevel", set_item_level)?
        .set_function("SetMouseOverFrame", set_mouse_over_frame)?
        .set_function("SetMousePosition", set_mouse_position)?
        .set_function("SetNetStats", set_net_stats)?
        .set_function("SetStoreFrameShown", set_store_frame_shown)?
        .set_function("SetTimerunningSeasonID", set_timerunning_season_id)?
        .set_function("SetZonePVP", set_zone_pvp)
}

fn register_modifier_keys(b: TableBuilder) -> LuaResult<TableBuilder> {
    b.set_function("SetShiftKeyDown", set_shift_key_down)?
        .set_function("SetControlKeyDown", set_control_key_down)?
        .set_function("SetAltKeyDown", set_alt_key_down)?
        .set_function("SetMetaKeyDown", set_meta_key_down)?
        .set_function(
            "IsSimulatorExitRequested",
            super::session_exit::is_simulator_exit_requested,
        )
}

fn register_guild_and_game_rules(b: TableBuilder) -> LuaResult<TableBuilder> {
    b.set_function("SetGuildEmblem", set_guild_emblem)?
        .set_function("SetGuildRanks", set_guild_ranks)?
        .set_function("SetGameRule", super::game_rules::admin_set_game_rule)?
        .set_function(
            "SetActiveGameMode",
            super::game_rules::admin_set_active_game_mode,
        )?
        .set_function("SetGuildClubId", super::guild_info::admin_set_guild_club_id)?
        .set_function(
            "SetGuildIsOfficer",
            super::guild_info::admin_set_guild_is_officer,
        )?
        .set_function(
            "SetGuildCanSpeakInChat",
            super::guild_info::admin_set_guild_can_speak_in_chat,
        )?
        .set_function("SetGuildMOTD", super::guild_info::admin_set_guild_motd)?
        .set_function(
            "SetGuildInfoText",
            super::guild_info::admin_set_guild_info_text,
        )?
        .set_function(
            "SetGuildChallenges",
            super::guild_info::admin_set_guild_challenges,
        )
}

fn register_services(b: TableBuilder) -> LuaResult<TableBuilder> {
    let b = register_housing_and_pet_battles(b)?;
    let b = register_lfg_services(b)?;
    register_photo_sharing(b)
}

fn register_housing_and_pet_battles(b: TableBuilder) -> LuaResult<TableBuilder> {
    b.set_function(
        "SetHousingServiceEnabled",
        super::housing::admin_set_housing_service_enabled,
    )?
    .set_function(
        "SetPetBattleCounts",
        super::pet_battles::admin_set_pet_battle_counts,
    )?
    .set_function(
        "SetPetBattleState",
        super::pet_battles::admin_set_pet_battle_state,
    )
}

fn register_lfg_services(b: TableBuilder) -> LuaResult<TableBuilder> {
    b.set_function(
        "SetLfgApplicationCounts",
        super::lfg_list::admin_set_application_counts,
    )?
    .set_function(
        "SetLfgApplicantCounts",
        super::lfg_list::admin_set_applicant_counts,
    )?
    .set_function(
        "SetCanUsePremadeGroup",
        crate::c_api::c_lfg_info::admin_set_can_use_premade_group,
    )?
    .set_function("GetLfgQueuePopDelay", get_lfg_queue_pop_delay)?
    .set_function("SetLfgQueuePopDelay", set_lfg_queue_pop_delay)
}

/// `A_Admin.GetLfgQueuePopDelay()` returns seconds from JoinLFG to proposal.
fn get_lfg_queue_pop_delay(state: &mut LuaState) -> LuaResult<u32> {
    let delay = borrow_state(state)?.lfg_queue_pop_delay_seconds;
    state.push(Val::Num(delay));
    Ok(1)
}

/// `A_Admin.SetLfgQueuePopDelay(seconds?)` configures the JoinLFG proposal
/// delay. Missing args reset to the default; invalid numeric values clamp to 0.
fn set_lfg_queue_pop_delay(state: &mut LuaState) -> LuaResult<u32> {
    let delay = Option::<f64>::from_stack(state, 1)?.unwrap_or(DEFAULT_LFG_QUEUE_POP_DELAY_SECONDS);
    borrow_state_mut(state)?.lfg_queue_pop_delay_seconds = valid_lfg_queue_pop_delay(delay);
    Ok(0)
}

fn valid_lfg_queue_pop_delay(delay: f64) -> f64 {
    if delay.is_finite() {
        delay.max(0.0)
    } else {
        0.0
    }
}

fn register_photo_sharing(b: TableBuilder) -> LuaResult<TableBuilder> {
    b.set_function(
        "SetPhotoSharingAuthorized",
        super::photo_sharing::admin_set_photo_sharing_authorized,
    )?
    .set_function(
        "SetPhotoSharingEnabled",
        super::photo_sharing::admin_set_photo_sharing_enabled,
    )
}

fn register_inventory_and_mail(b: TableBuilder) -> LuaResult<TableBuilder> {
    let b = b
        .set_function("SetActionSlot", set_action_slot)?
        .set_function("SetPetActionSlot", set_pet_action_slot)?
        .set_function("ClearActionSlot", clear_action_slot)?
        .set_function("ClearActionBars", clear_action_bars)?
        .set_function("AddBagItem", add_bag_item)?
        .set_function("RemoveBagItem", remove_bag_item)?
        .set_function("ClearBags", clear_bags)?
        .set_function("AddGuildBankItem", add_guild_bank_item)?
        .set_function("ClearGuildBank", clear_guild_bank)?
        .set_function("AddMail", add_mail)?
        .set_function("ClearInbox", clear_inbox)?
        .set_function("OpenMailbox", open_mailbox)?
        .set_function("CloseMailbox", close_mailbox)?
        .set_function("SetInboxCount", set_inbox_count)?;

    register_auction_house_admin(b)
}

fn register_auction_house_admin(b: TableBuilder) -> LuaResult<TableBuilder> {
    b.set_function("AddAuctionBrowseResult", add_auction_browse_result)?
        .set_function("ClearAuctionBrowseResults", clear_auction_browse_results)?
        .set_function("AddAuctionItemSearchResult", add_auction_item_search_result)?
        .set_function(
            "ClearAuctionItemSearchResults",
            clear_auction_item_search_results,
        )?
        .set_function(
            "AddAuctionCommoditySearchResult",
            add_auction_commodity_search_result,
        )?
        .set_function(
            "ClearAuctionCommoditySearchResults",
            clear_auction_commodity_search_results,
        )?
        .set_function("SetAuctionThrottleReady", set_auction_throttle_ready)?
        .set_function("AddAuctionReplicateItem", add_auction_replicate_item)?
        .set_function("ClearAuctionReplicateItems", clear_auction_replicate_items)?
        .set_function("AddOwnedAuction", add_owned_auction)?
        .set_function("ClearOwnedAuctions", clear_owned_auctions)?
        .set_function("AddAuctionBid", add_auction_bid)?
        .set_function("ClearAuctionBids", clear_auction_bids)
}

fn register_vault_and_premade(b: TableBuilder) -> LuaResult<TableBuilder> {
    b.set_function("SetVaultActivity", set_vault_activity)?
        .set_function("SetVaultRewards", set_vault_rewards)?
        .set_function("ClearVault", clear_vault)?
        .set_function("AddPremadeListing", add_premade_listing)?
        .set_function("ClearPremadeListings", clear_premade_listings)?
        .set_function("UpdatePremadeListing", update_premade_listing)
}

fn register_collections_pvp<'lua>(b: TableBuilder<'lua>) -> LuaResult<TableBuilder<'lua>> {
    register_functions(b, COLLECTIONS_PVP_FUNCTIONS)
}

const COLLECTIONS_PVP_FUNCTIONS: &[(&str, RustFn)] = &[
    ("AddTransmog", add_transmog),
    ("RemoveTransmog", remove_transmog),
    ("AddTransmogAppearance", add_transmog_appearance),
    ("SetTransmogForSlot", set_transmog_for_slot),
    ("CollectHeirloom", collect_heirloom),
    ("UncollectHeirloom", uncollect_heirloom),
    ("SetMountCollected", set_mount_collected),
    ("SetPetCollected", set_pet_collected),
    ("SetToyCollected", set_toy_collected),
    ("SetCampsiteCollected", set_campsite_collected),
    ("SetAchievementEarned", set_achievement_earned),
    ("HasAchievement", has_achievement),
    ("SetMerchantItems", set_merchant_items),
    ("CollectMount", collect_mount),
    ("UncollectMount", uncollect_mount),
    ("CollectPet", collect_pet),
    ("UncollectPet", uncollect_pet),
    ("CollectToy", collect_toy),
    ("UncollectToy", uncollect_toy),
    ("CollectCampsite", collect_campsite),
    ("UncollectCampsite", uncollect_campsite),
    ("EarnAchievement", earn_achievement),
    ("SetPvPEnabled", set_pvp_enabled),
    ("SetHonorLevel", set_honor_level),
    ("SetGuildInfo", set_guild_info),
    ("JoinGuild", join_guild),
    ("ClearGuild", clear_guild),
    ("LeaveGuild", leave_guild),
];

fn register_functions<'lua>(
    mut builder: TableBuilder<'lua>,
    functions: &[(&str, RustFn)],
) -> LuaResult<TableBuilder<'lua>> {
    for (name, func) in functions {
        builder = builder.set_function(name, *func)?;
    }
    Ok(builder)
}

fn register_inventory_misc(b: TableBuilder) -> LuaResult<TableBuilder> {
    let b = b
        .set_function("FireEvent", fire_event_admin)?
        .set_function("ToggleDebugBorders", toggle_debug_borders)?
        .set_function("ToggleDebugAnchors", toggle_debug_anchors)?;
    let b = super::admin_quests::register_quests(b)?
        .set_function("SimulateBossKill", simulate_boss_kill)?
        .set_function("AddLootItem", add_loot_item)?
        .set_function("ClearLoot", clear_loot)?
        .set_function("GetLastLootRollChoice", get_last_loot_roll_choice)?
        .set_function("StartLootRoll", start_loot_roll)?
        .set_function("EndLootRoll", end_loot_roll)?;
    register_crafting(b)
}

fn register_crafting(b: TableBuilder) -> LuaResult<TableBuilder> {
    b.set_function("LearnRecipe", learn_recipe)?
        .set_function("UnlearnRecipe", unlearn_recipe)?
        .set_function("ClearKnownRecipes", clear_known_recipes)?
        .set_function("SetSelectedProfession", set_selected_profession)?
        .set_function("UnlearnProfession", unlearn_profession)?
        .set_function("RelearnProfession", relearn_profession)?
        .set_function("SetReagentCount", set_reagent_count)?
        .set_function("SeedReagentsForRecipe", seed_reagents_for_recipe)?
        .set_function("RegisterTestAddon", register_test_addon)
}

// ── Player identity ──────────────────────────────────────────────────────────

fn set_player_name(state: &mut LuaState) -> LuaResult<u32> {
    let name = String::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.name = name;
    Ok(0)
}

fn set_player_class(state: &mut LuaState) -> LuaResult<u32> {
    let class_index = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.class_index = class_index;
    Ok(0)
}

fn set_player_race(state: &mut LuaState) -> LuaResult<u32> {
    let race_index = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.race_index = race_index as usize;
    Ok(0)
}

fn set_player_level(state: &mut LuaState) -> LuaResult<u32> {
    let level = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.level = level;
    Ok(0)
}

fn set_player_sex(state: &mut LuaState) -> LuaResult<u32> {
    let sex = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.sex = sex;
    Ok(0)
}

// ── Combat ───────────────────────────────────────────────────────────────────

fn set_in_combat(state: &mut LuaState) -> LuaResult<u32> {
    let v = bool::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.in_combat = v;
    Ok(0)
}

fn set_resting(state: &mut LuaState) -> LuaResult<u32> {
    let v = bool::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.is_resting = v;
    Ok(0)
}

fn set_frame_protected(state: &mut LuaState) -> LuaResult<u32> {
    let name = String::from_stack(state, 1)?;
    let v = bool::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    if let Some(id) = st.widgets.get_id_by_name(&name)
        && let Some(frame) = st.widgets.get_mut(id)
    {
        frame.is_protected = v;
    }
    Ok(0)
}

// ── Casting & cooldowns ──────────────────────────────────────────────────────

fn set_casting(state: &mut LuaState) -> LuaResult<u32> {
    let spell_id = u32::from_stack(state, 1)?;
    let spell_name = String::from_stack(state, 2)?;
    let icon_path = String::from_stack(state, 3)?;
    let duration = f64::from_stack(state, 4)?;
    let mut st = borrow_state_mut(state)?;
    let now = st.runtime_time_seconds();
    let cast_id = st.next_cast_id;
    st.next_cast_id += 1;
    st.casting = Some(CastingState {
        spell_id,
        spell_name,
        icon_path,
        start_time: now,
        end_time: now + duration,
        cast_id,
        num_empower_stages: 0,
    });
    Ok(0)
}

fn stop_casting(state: &mut LuaState) -> LuaResult<u32> {
    borrow_state_mut(state)?.casting = None;
    Ok(0)
}

fn set_gcd(state: &mut LuaState) -> LuaResult<u32> {
    let duration = f64::from_stack(state, 1)?;
    let mut st = borrow_state_mut(state)?;
    let now = st.runtime_time_seconds();
    st.gcd = Some((now, duration));
    Ok(0)
}

fn set_spell_cooldown(state: &mut LuaState) -> LuaResult<u32> {
    let spell_id = u32::from_stack(state, 1)?;
    let duration = f64::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    let now = st.runtime_time_seconds();
    st.spell_cooldowns.insert(
        spell_id,
        SpellCooldownState {
            start: now,
            duration,
        },
    );
    Ok(0)
}

// ── Health & power ───────────────────────────────────────────────────────────

fn set_player_health(state: &mut LuaState) -> LuaResult<u32> {
    let cur = i32::from_stack(state, 1)?;
    let max = i32::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    st.player.health = cur;
    st.player.health_max = max;
    Ok(0)
}

fn set_player_power(state: &mut LuaState) -> LuaResult<u32> {
    let cur = i32::from_stack(state, 1)?;
    let max = i32::from_stack(state, 2)?;
    let power_type = Option::<i32>::from_stack(state, 3)?;
    let mut st = borrow_state_mut(state)?;
    if let Some(pt) = power_type {
        if is_secondary_player_power_type(pt) {
            st.player
                .secondary_powers
                .insert(pt, SecondaryPowerState { current: cur, max });
            return Ok(0);
        }
        st.player.power_type = pt;
    }
    st.player.power = cur;
    st.player.power_max = max;
    Ok(0)
}

fn is_secondary_player_power_type(power_type: i32) -> bool {
    matches!(
        power_type,
        4 | 5 | 6 | 7 | 8 | 9 | 11 | 12 | 13 | 16 | 17 | 18
    )
}

fn set_target_health(state: &mut LuaState) -> LuaResult<u32> {
    let cur = i32::from_stack(state, 1)?;
    let max = i32::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    if let Some(t) = st.current_target.as_mut() {
        t.health = cur;
        t.health_max = max;
    }
    Ok(0)
}

// ── Internal helpers ──────────────────────────────────────────────────────────

/// Build an AuraInfo for admin-added buffs.
pub(super) fn build_admin_buff(
    st: &crate::lua_api::state::SimState,
    spell_id: i32,
    name: String,
    icon: String,
    duration: f64,
    stacks: i32,
) -> AuraInfo {
    build_admin_aura(st, spell_id, name, icon, duration, stacks, true, None)
}

/// Build an AuraInfo for admin-added auras (buffs or debuffs).
#[allow(clippy::too_many_arguments)]
pub(super) fn build_admin_aura(
    st: &crate::lua_api::state::SimState,
    spell_id: i32,
    name: String,
    icon: String,
    duration: f64,
    stacks: i32,
    is_helpful: bool,
    dispel_type: Option<String>,
) -> AuraInfo {
    let expiration_time = if duration > 0.0 {
        st.runtime_time_seconds() + duration
    } else {
        0.0
    };
    AuraInfo {
        name,
        spell_id,
        icon: icon.parse::<i32>().unwrap_or(0),
        duration,
        expiration_time,
        applications: stacks,
        source_unit: "player".to_string(),
        is_helpful,
        is_stealable: false,
        can_apply_aura: is_helpful,
        is_from_player_or_player_pet: is_helpful,
        dispel_type,
        aura_instance_id: (st.player.buffs.len() + 1) as i32,
    }
}

/// Build a MailMessage for admin inbox functions.
pub(crate) fn build_mail(
    id: u64,
    sender: String,
    subject: String,
    body: String,
    money: u64,
    items: Vec<crate::lua_api::state_types::MailAttachment>,
) -> crate::lua_api::state_types::MailMessage {
    crate::lua_api::state_types::MailMessage {
        id,
        sender,
        subject,
        body,
        money,
        cod_amount: 0,
        items,
        days_left: 30.0,
        was_read: false,
        was_returned: false,
        can_reply: true,
        is_gm: false,
        stationery_icon: 0,
    }
}

/// Extract a string from the stack, returning a default if nil or absent.
pub(super) fn opt_string_stack(state: &LuaState, index: i32, default: &str) -> String {
    match crate::lua_bridge::stack_val(state, index) {
        Val::Str(s) => state
            .gc
            .string_arena
            .get(s)
            .map(|ls| String::from_utf8_lossy(ls.data()).into_owned())
            .unwrap_or_else(|| default.to_string()),
        _ => default.to_string(),
    }
}
